Added the coming soon and news section
QAZIMAAZARSHAD/Movie-Streaming-Website pull request #497
Opened 2021-08-05 11:05 UTC by Srijan1878

#### Fixes #(issue number)
      Fixes #106  

 

#### Describe the changes you've made
Added the coming soon slider and also made a news section footer which has been termed as "coming soon"

#### Deploy your changes to github page or netlify and mention deployment link:
https://vigilant-hopper-0959a5.netlify.app/
![Screenshot (352)](https://user-images.githubusercontent.com/80585719/128340059-2c506ef3-ff4a-4af9-81bc-d3cb06144262.png)
![Screenshot (353)](https://user-images.githubusercontent.com/80585719/128340066-deb300e6-4141-403a-a210-37478fe6d144.png)
![Screenshot (354)](https://user-images.githubusercontent.com/80585719/128340067-ed8c05d0-ec2d-4dfa-9aef-f64ab8c6675c.png)

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

#### Additional context (OPTIONAL)
Add any other context or screenshots about the feature request here.

#### Test plan (OPTIONAL)
A good test plan should give instructions that someone else can easily follow.
How someone can test your code?

#### Checklist

- [x] I have mentioned related issue number in PR description.
- [x] I have added screenshots and related demo links of my changes..
- [x] The title of my pull request is a short description of the requested changes.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here)LGMSOC

2021-08-05 11:07 UTC, Srijan1878 commented
This is a new PR for the coming soon page. I was facing some trouble while making changes for the previous PR, so I had to this.
I hope this time it's okay. @QAZIMAAZARSHAD

2021-08-05 11:21 UTC, QAZIMAAZARSHAD commented
Your repo is not updated.
You have deleted the new navbar update.

Add a footer to the news page.

Remove the news slider from the home page.

2021-08-05 11:40 UTC, Srijan1878 commented
Please check the updates through the netlify link, I have updated it there too.

2021-08-05 12:07 UTC, QAZIMAAZARSHAD commented
Check the scroll to the top button on the news page.

Rename new to "Coming Soon".

Remove unnecessary CSS you added in home.html.

Change content on the Coming soon page like rename 'Netflix', 'Hulu', to 'Apna Theatre'.

2021-08-05 15:43 UTC, Srijan1878 commented
Please have a look now @QAZIMAAZARSHAD

2021-08-05 16:17 UTC, QAZIMAAZARSHAD requested changes

2021-08-05 16:17 UTC, QAZIMAAZARSHAD commented on home.html
> +.titleTextContainer{
@Srijan1878 I was talking about this CSS.

Is this of any use?

2021-08-06 06:06 UTC, Srijan1878 commented
I removed the unused CSS of the slider which had been deleted, please have a look. @QAZIMAAZARSHAD

2021-08-06 06:51 UTC, QAZIMAAZARSHAD approved these changes

2021-08-06 06:52 UTC, merged

2021-08-06 06:56 UTC, QAZIMAAZARSHAD commented
![image](https://user-images.githubusercontent.com/56196640/128469190-4f9f92ac-29d0-47f6-8746-b9ea3ca8f695.png)

Make one PR to correct this.